name: icl_nocentos
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - absl-py=2.2.0=pyhd8ed1ab_0
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - aom=3.9.1=hac33072_0
  - appdirs=1.4.4=pyhd8ed1ab_1
  - blosc=1.21.6=he440d0b_1
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - brotli-python=1.1.0=py311hfdbb021_2
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.1.31=hbcca054_0
  - certifi=2025.1.31=pyhd8ed1ab_0
  - cffi=1.17.1=py311hf29c0ef_0
  - charset-normalizer=3.4.1=pyhd8ed1ab_0
  - chex=0.1.88=pyhd8ed1ab_1
  - click=8.1.8=pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.2=py311hd18a35c_0
  - cuda-version=11.8=h70ddcb2_3
  - cudatoolkit=11.8.0=h4ba93d1_13
  - cudnn=9.3.0.75=hc149ed2_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - dav1d=1.2.1=hd590300_0
  - docker-pycreds=0.4.0=py_0
  - docstring_parser=0.16=pyhd8ed1ab_0
  - etils=1.12.2=pyhd8ed1ab_0
  - eval_type_backport=0.2.2=pyha770c72_0
  - flax=0.10.2=pyhd8ed1ab_0
  - fonttools=4.57.0=py311h2dc5d0c_0
  - freetype=2.13.3=h48d6fc4_0
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.44=pyhff2d567_0
  - h2=4.2.0=pyhd8ed1ab_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - humanize=4.12.2=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.6.1=pyha770c72_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - jaxopt=0.8.4=pyhd8ed1ab_0
  - kernel-headers_linux-64=3.10.0=he073ed8_18
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.7=py311hd18a35c_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - lerc=4.0.0=h27087fc_0
  - libabseil=20250127.1=cxx17_hbbce691_0
  - libavif16=1.2.1=hbb36593_2
  - libblas=3.9.0=31_h59b9bed_openblas
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcblas=3.9.0=31_he106b2a_openblas
  - libcurl=8.13.0=h332b0f4_0
  - libdeflate=1.23=h4ddbbb0_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgfortran=14.2.0=h69a702a_2
  - libgfortran5=14.2.0=hf1ad2bd_2
  - libgomp=14.2.0=h767d61c_2
  - libgrpc=1.71.0=he753a82_0
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=31_h7ac8fdf_openblas
  - liblzma=5.8.1=hb9d3cd8_0
  - liblzma-devel=5.8.1=hb9d3cd8_0
  - libnghttp2=1.64.0=h161d5f1_0
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.29=pthreads_h94d23a6_0
  - libpng=1.6.47=h943b412_0
  - libprotobuf=5.29.3=h501fc15_0
  - libre2-11=2024.07.02=hba17884_3
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.11.1=hf672d98_0
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-ng=14.2.0=h4852527_2
  - libtiff=4.7.0=hd9ff511_3
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - lz4-c=1.10.0=h5888daf_1
  - markdown-it-py=3.0.0=pyhd8ed1ab_1
  - matplotlib-base=3.10.1=py311h2b939e6_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - ml_dtypes=0.5.1=py311h7db5c69_0
  - msgpack-python=1.1.0=py311hd18a35c_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numpy=2.2.4=py311h5d046bc_0
  - openjpeg=2.5.3=h5fbd93e_0
  - openssl=3.5.0=h7b32b05_0
  - opt_einsum=3.4.0=pyhd8ed1ab_1
  - optax=0.2.4=pyhd8ed1ab_1
  - orbax-checkpoint=0.6.4=pyhd8ed1ab_1
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=2.2.3=py311h7db5c69_3
  - patsy=1.0.1=pyhd8ed1ab_1
  - pillow=11.1.0=py311h1322bbf_0
  - pip=25.0.1=pyh8b19718_0
  - platformdirs=4.3.7=pyh29332c3_0
  - protobuf=5.29.3=py311h3a6f5f3_0
  - psutil=7.0.0=py311h9ecbd09_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pybind11-abi=4=hd8ed1ab_3
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.11.3=pyh3cfb1c2_0
  - pydantic-core=2.33.1=py311h687327b_0
  - pygments=2.19.1=pyhd8ed1ab_0
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.11.9=hb806964_0_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.11=6_cp311
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py311h2dc5d0c_2
  - qhull=2020.2=h434a139_5
  - rav1e=0.6.6=he8a937b_2
  - re2=2024.07.02=h9925aae_3
  - readline=8.2=h8c095d6_2
  - requests=2.32.3=pyhd8ed1ab_1
  - rich=14.0.0=pyh29332c3_0
  - scipy=1.15.2=py311h8f841c2_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - sentry-sdk=2.26.1=pyhd8ed1ab_0
  - setproctitle=1.3.5=py311h9ecbd09_0
  - setuptools=78.1.0=pyhff2d567_0
  - shtab=1.7.2=pyhd8ed1ab_0
  - six=1.17.0=pyhd8ed1ab_0
  - smmap=5.0.2=pyhd8ed1ab_0
  - snappy=1.2.1=h8bd8927_1
  - statsmodels=0.14.4=py311h9f3472d_0
  - svt-av1=3.0.2=h5888daf_0
  - sysroot_linux-64=2.17=h0157908_18
  - tensorstore=0.1.65=py311h9116a42_5
  - tk=8.6.13=noxft_h4845f30_101
  - toolz=1.0.0=pyhd8ed1ab_1
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typeguard=4.4.2=pyhd8ed1ab_0
  - typing=3.10.0.0=pyhd8ed1ab_2
  - typing-extensions=4.13.2=h0e9735f_0
  - typing-inspection=0.4.0=pyhd8ed1ab_0
  - typing_extensions=4.13.2=pyh29332c3_0
  - tyro=0.9.18=pyhd8ed1ab_0
  - tzdata=2025b=h78e105d_0
  - unicodedata2=16.0.0=py311h9ecbd09_0
  - urllib3=2.4.0=pyhd8ed1ab_0
  - wandb=0.19.9=py311h9e33e62_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xz=5.8.1=hbcc6ac9_0
  - xz-gpl-tools=5.8.1=hbcc6ac9_0
  - xz-tools=5.8.1=hb9d3cd8_0
  - yaml=0.2.5=h7f98852_2
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.23.0=py311h9ecbd09_1
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - jax==0.6.0
      - jax-cuda12-pjrt==0.6.0
      - jax-cuda12-plugin==0.6.0
      - jaxlib==0.6.0
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvcc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.8.0.87
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-nccl-cu12==2.26.2.post1
      - nvidia-nvjitlink-cu12==12.8.93
      - simple-pytree==0.2.2
prefix: /home/jhays/.conda/envs/icl
